version: "3.8"

services:
  be-api:
    # container_name: be-api
    env_file:
      - .env
    build:
      context: .
      #dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/src
    ports:
      - "3001:3001"
    command: npm run dev
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    depends_on:
      - postgres

  postgres:
    image: postgres:13.0
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      -  postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: quiz-db
